# -*- coding: utf-8 -*-
"""Convidados.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CwxC3KEXybcfp-RlXm-naqpqToe3-FvZ
"""

convidados = []
pesfq = input(f'\nQuantas pessoas você convidará ?\t')
pesfqN = int(pesfq)
for c in range(0, pesfqN):
  con = (input('\nQuem você convidará ?\t'))
  con1 = con.upper()
  convidados.append(con1)
print()
lista = (f'\nVocês foram convidados para a minha festa:\t')
print(lista + str(convidados))
naovira = input(f'\nAlguém não poderá vir ?\t')
naovira2 = naovira.lower()
conS = 'sim' #definir mais str de respostas positivas
conSN = 'não' #definir mais srt de respostas negativas
if naovira2 == conS:
  qunNf = input(f'\nQuantas pessoas não poderão vir ?\t')
  qunNfN = int(qunNf)
  for nc in range(0, qunNfN):
    naovira2 = input(f'\nQuem não poderá vir ?\t')
    naovira2mai = naovira2.upper()
    convidados.remove(naovira2mai)
 
else:
  print(f'\nNão faltará ninguém')
 
print(f'\nLista atualizada da festa\t' + str(convidados))
print(f'\nEles estão confirmados:\t' + str(convidados))
 
if naovira == conS:
  dis = input(f'\nVocê quer convidar mais alguém ? Há ' + str(qunNfN) + ' vagas disponíveis:\t') 
  mindis = dis.lower()
  for nc2 in range(0, qunNfN):
    vira = input(f'\nQuem você convidará ?\t')
    viramai = vira.upper()
    convidados.append(viramai)
else:
  print(f'\nA lista de confirmados se mantém e há ' + str(len(convidados)) + ' confirmados')
 
print(f'\nlista atualizada para a festa:\t' + str(convidados))
 
naovir3 = input(f'\nMais alguém não poderá vir ?\t')
minnaovir3 = naovir3.lower()
 
if minnaovir3 == conS:
  QuanN = input(f'\nQuantos não poderão vir ?\t')
  QuanN2 = int(QuanN)
  for nc3 in range(0, QuanN2):
    naovir3_1 = input(f'\nQuem não virá mais ?\t')
    naovir3_1mai = naovir3_1.upper()
    convidados.remove(naovir3_1mai)
 
else:
  print('\nLista atualizada ' + str(convidados))
 
print(f'\nLista final de convidados ' + str(convidados))
 
print(f'\nMuito obrigado pela suas presenças:\t' + str(convidados))

